version: 1.0.{build}
clone_depth: 1

os: Visual Studio 2015
image: Visual Studio 2015

platform:
    - x64

environment:
    matrix:
        - PYTHON: C:\Python27-x64
matrix:
    fast_finish: true

install:
  - IF DEFINED PYTHON %PYTHON%\python -m pip install --user numpy pandas matplotlib wheel setuptools

before_build:
    - IF DEFINED PYTHON SET LANG=%LANG% -DPYTHON_EXECUTABLE=%PYTHON%\python.exe

build_script:
    - mkdir build
    - ps: pushd build
    - cmake C:\projects\libecl "-GVisual Studio 14 2015 Win64" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=pip
    - cmake --build . --config pip --target install
    - ps: popd
    - ps: pushd python
    - cat setup.py
    - %PYTHON%\python setup.py build
    - ps: popd
